GO
ALTER DATABASE [XBankDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [XBankDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [XBankDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [XBankDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [XBankDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [XBankDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [XBankDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [XBankDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [XBankDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [XBankDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [XBankDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [XBankDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [XBankDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [XBankDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [XBankDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [XBankDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [XBankDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [XBankDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [XBankDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [XBankDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [XBankDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [XBankDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [XBankDB] SET RECOVERY FULL 
GO
ALTER DATABASE [XBankDB] SET  MULTI_USER 
GO
ALTER DATABASE [XBankDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [XBankDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [XBankDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [XBankDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [XBankDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [CarRentalDB]
GO



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Companies](
	[CompanyID] [int] IDENTITY(1,1) NOT NULL,
	[CompanyName] [nvarchar](50) NOT NULL,
	[City] [nvarchar](50) NOT NULL,
	[Address] [nvarchar](50) NOT NULL,
	[TotalCars] [int] NOT NULL,
 CONSTRAINT [PK_tbl_Companies] PRIMARY KEY CLUSTERED 
(
	[CompanyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


/* //// */


GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_Cars](
	[CarID] [int] IDENTITY(1,1) NOT NULL,
	[CarName] [nvarchar](50) NOT NULL,
	[CarModel] [nvarchar](50) NOT NULL,
	[RentFeeDaily] [money] NOT NULL,
	[CarTotalKM] [int] NOT NULL,
	[CarTotalSeats] [int] NOT NULL,
	[isRent] [bit] NOT NULL,
 CONSTRAINT [PK_tbl_Cars] PRIMARY KEY CLUSTERED 
(
	[CarID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


USE [master]
GO
ALTER DATABASE [CarRentalDB] SET  READ_WRITE 
GO


/*
GO
ALTER TABLE [dbo].[tbl_Transactions]  WITH CHECK ADD  CONSTRAINT [FK_tbl_Transactions_tbl_Customers1] FOREIGN KEY([TransactorAccountNumber])
REFERENCES [dbo].[tbl_Customers] ([CustomerID])
GO
ALTER TABLE [dbo].[tbl_Transactions] CHECK CONSTRAINT [FK_tbl_Transactions_tbl_Customers1]
GO

*/